### ISSUE TITLE
Call `invariant_mass` just `mass`

### ISSUE THREAD

**Issue by mmikhasenko** [JuliaHEP/LorentzVectorBase.jl#1]
- [x] Call `invariant_mass` just `mass`
- [x] `invariant_mass2` -> `mass2`, or `mass_squared`
- [x] `momentum_squared` instead of `magnitude`

**Comment by TheFibonacciEffect** [comment]
renamed `magnitude` to `spacial_magnitude`

**Comment by TheFibonacciEffect** [comment]
so for the last one I used `spatial_magintude`

**Comment by mmikhasenko** [comment]
Solved
